movies pipeline project done
volodymyrkir/python-education pull request #32
Opened 2022-06-19 15:44 UTC by volodymyrkir

2022-06-21 20:16 UTC, ikalchenko requested changes

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/dags/python_jobs/load_data_demand.py
> +API_KEY = 'a76a378f657bde880c649956809cb6c6'
Please use env vars or Airflow vars instead of storing it hardcoded

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/dags/spark_jobs/join_imdb_tmdb_data.py
> +            .execute('ALTER TABLE film_tmdb_imdb ADD COLUMN IF NOT EXISTS average_rating double precision')
All these requests could be separate steps of the DAG instead of being part of the spark job

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/dags/python_jobs/load_data_demand.py
> +    three_month_back = (datetime.now() - relativedelta(months=3)).strftime('%Y-%m-%d')
It'd be great to have ability to configure this period before the DAG run

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/dags/spark_jobs/load_daily_films_postgres.py
> +def fetch_json_files(s3, bucket_name: str = "raw-data"):
It's better to load data using spark, instead of reading using python and then creating DF from data
it could be lots of data and job will fail because of that

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/dags/spark_jobs/load_daily_films_postgres.py
> +    return dataframe.filter(~dataframe.id.isin(list_of_keys)).toPandas()
it shouldn't be converted to pandas, cos there could be a lot of data and the job will fail with OOM

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/dags/spark_jobs/load_daily_films_postgres.py
> +            tmdb_dataframe.to_sql('film_tmdb_imdb',
It's better to use spark to write data to database

2022-06-21 20:16 UTC, ikalchenko commented on imdb_project/.env
> +MINIO_ROOT_USER=minio_access_key
it's better to push sample.env with dummy values but locally have actual vars

2022-06-22 08:41 UTC, volodymyrkir commented on imdb_project/dags/spark_jobs/load_daily_films_postgres.py
> +    return dataframe.filter(~dataframe.id.isin(list_of_keys)).toPandas()
it is converted to pandas due to alchemy approach, i will try my best to replace it

2022-07-06 07:06 UTC, merged